name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE] <title>"
labels: ["enhancement"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing feature request for this?
      description: Please search to see if a similar feature request already exists.
      options:
        - label: I have searched the existing requests
          required: true
  - type: textarea
    attributes:
      label: Description
      description: Provide a clear and detailed description of the new feature or improvement.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use Case
      description: Explain how this feature would benefit users or improve the overall experience.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: If you have any ideas on how to implement the feature, share them here.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features? If so, please describe them.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: Provide any additional information, context, or references that may help understand the feature request better.
    validations:
      required: false
