describe("actions", function()
    it("should return a table", function()
        local actions = require("seshmgr.actions")
        assert(actions ~= nil)
    end)

    it("should have a load function", function()
        local actions = require("seshmgr.actions")
        assert.is_function(actions.load_session)
    end)

    it("should have a save function", function()
        local actions = require("seshmgr.actions")
        assert.is_function(actions.save_session)
    end)

    it("should have a delete function", function()
        local actions = require("seshmgr.actions")
        assert.is_function(actions.delete_session)
    end)

    it("should have an exists function", function()
        local actions = require("seshmgr.actions")
        assert.is_function(actions.session_exists)
    end)

    it("should have a get_sessions function", function()
        local actions = require("seshmgr.actions")
        assert.is_function(actions.get_sessions)
    end)

    it("should have a get_session_file function", function()
        local actions = require("seshmgr.actions")
        assert.is_function(actions.get_session_file_path)
    end)
end)
