describe("init", function()
    it("should return a table", function()
        local init = require("seshmgr")
        assert(init ~= nil)
    end)

    it("should use opts over default config", function()
        local init = require("seshmgr")
        assert.not_equal("test", init.config.session_file)
        init.setup({ session_dir = "test" })
        assert.equal("test", init.config.session_dir)
    end)
end)
