describe("init", function()
    it("should return a table", function()
        local init = require("seshmgr")
        assert(init ~= nil)
    end)

    it("should use opts over default config", function()
        local init = require("seshmgr")
        assert(init.config.session_dir ~= "test", init.config.session_dir)
        init.setup({ session_dir = "test" })
        assert(init.config.session_dir == "test", "session_dir")
    end)
end)
